### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by kylophone** [audionuma/r128x#5]
I think that there is a memory leak somewhere in the code, but I can't find it. Open activity monitor while processing a large file and you'll see that after a file is processed, memory is not reclaimed by the OS. Anyone else experiencing something similar?

**Comment by audionuma** [comment]
Found a leaking CFnumberRef in r128x/ExtAudioProcessor.c.
See commit https://github.com/audionuma/r128x/commit/123307d2175e7682875b99d473f616f35c3906cb
Hope it solves this issue. Marked as closed until further notice.
