### ISSUE TITLE
Installation question.

### ISSUE THREAD

**Issue by eloiseplz** [audionuma/r128x#6]
I'm a newbie...so forgive me if I ask an obvious-seeming question.
Which is the r128x executable file? I downloaded the zip, but I don't see a dmg.

**Comment by audionuma** [comment]
Hello,
as github doesn't allow to host binaries, you have to download the executable from my dropbox shared files : 
r128x-cli https://www.dropbox.com/s/59dfxzum42jc82v/r128x-cli-0-21.zip
r128x-gui https://www.dropbox.com/s/tzkwccqhkybsn3q/r128x-gui-0-21.zip
as explained in the readme.md.
There are no dmg, the zip archives contain the executable that you can copy on your system.
