### ISSUE TITLE
Measurements for "input threshold" and "target offset"

### ISSUE THREAD

**Issue by pnbv** [audionuma/r128x#7]
Hi, 
Is it possible to add "input threshold" and "target offset" to output? Or do you know if these are calculated from IL, LRA and TP.
I'm looking into using r128x-cli for the initial (measurement) step of audio normalisation using ffmpeg's loudnorm filter. This would require all the measurements made by ffmpeg's loudnorm 1st pass which include "input threshold" and "target offset".
Thank you.

**Comment by pnbv** [comment]
Ok, I've checked libebur128 and there's a "ebur128_relative_threshold" that seems to be one of the values needed.
Is this a question of version numbers (can I simply use a more recent version)?
Thanks again.

**Comment by audionuma** [comment]
Hello,
there's no plan from me to support this functionality in r128x.
If you plan to use FFmpeg's loudnorm filter, why don't you go with FFmpeg for the initial measurement ?

**Comment by pnbv** [comment]
Hi, 
Indeed, that is what I'm doing. But I've found r128x to be much faster and wondered about having it make the 1st measuring pass. This since I'm already using r128x for flagging files for audio normalisation.
But thank you anyway!
